

# Background color of the main area
backgroundColor = "#ffffff"

# Background color of the sidebar
secondaryBackgroundColor = "#f0f2f6"

# Text color
textColor = "#262730"

# Font style. Options: "sans serif", "serif", or "monospace"
font = "sans serif"
